dist: trusty

language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.2
      env: SYMFONY_VERSION="^4.1"
    - php: 7.3
      env: SYMFONY_VERSION="^4.1"
    - php: 7.3
      env: SYMFONY_VERSION="^5.0"
  fast_finish: true

before_install:
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi

install:
  # use "update" instead of "install" since it allows using the "--prefer-lowest" option
  - composer update $COMPOSER_FLAGS

script:
  - php ./vendor/bin/phpunit
