dist: trusty

language: php

php:
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.2
      env: EXTRA_PACKAGES="doctrine/phpcr-bundle:^1.3 brianium/paratest:^1.0 doctrine/phpcr-odm:^1.3"
  allow_failures:
    - php: 7.2
      env: SYMFONY_VERSION="dev-master"
  fast_finish: true

before_install:
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - if [ "$EXTRA_PACKAGES" != "" ]; then composer require --no-update $EXTRA_PACKAGES; fi

install:
  # use "update" instead of "install" since it allows using the "--prefer-lowest" option
  - composer update $COMPOSER_FLAGS

# http://jubianchi.fr/how-to-test-your-symfony2-project-with-behat-on-travisci.htm
before_script:
  - mysql -u root -e 'CREATE DATABASE liip;'

# In phpunit.xml.dist, tests annotated with "@group mysql" are excluded,
# revert this.
script: php ./vendor/bin/phpunit --exclude-group ""
