name: QA

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Delete composer files to avoid installing dependencies
        run: rm -v composer.json

      - name: PHP-CS-Fixer
        uses: docker://jakzal/phpqa:1.58.7-php7.4-alpine
        with:
          args: php-cs-fixer --dry-run --diff --no-interaction --ansi fix

  composer-validate:
    name: Composer validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Composer validate
        uses: docker://composer:2
        with:
          args: composer validate --strict
